url: "https://notes.99000000.xyz"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "notes/"
    values:
      css: "styles"
  - scope:
      path: ""
    values:
      css: "styles"
  - scope:
      path: "articles/"
    values:
      css: "article"

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%Y-%m-%d'
